# Generated by Django 4.2.7 on 2023-12-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Phone', models.IntegerField()),
                ('Salary', models.TextField()),
            ],
        ),
    ]
